### ISSUE TITLE
你好，是否能够共享一下你的中文翻译文件

### ISSUE THREAD

**Issue by gghyoo** [YI-BOYANG/inav-configurator-chinese#1]

**Comment by YI-BOYANG** [comment]
gitee开源地址：https://gitee.com/YI_BOYANG/inav-configurator-chinese
之前试过从gitee中把仓库克隆到github没成功，所以就一直没管了。gitee没法上传超过100M的程序，所以打包好的中文地面站放在微盘里了，微盘链接：https://drive.weixin.qq.com/s?k=AFkApQJVAFg5bw1PI8

**Comment by YI-BOYANG** [comment]
6.0.0中文版已发布
